#stage population
Stage.create(name: "Final Destination", legality: "Neutral")
Stage.create(name: "Fountain of Dreams", legality: "Neutral")
Stage.create(name: "Battlefield", legality: "Neutral")
Stage.create(name: "Dream Land (N64)", legality: "Neutral")
Stage.create(name: "Yoshi's Story", legality: "Neutral")

Stage.create(name: "Pokémon Stadium", legality: "Counterpick")

Stage.create(name: "Big Blue", legality: "Gentleman")
Stage.create(name: "Brinstar", legality: "Gentleman")
Stage.create(name: "Brinstar Depths", legality: "Gentleman")
Stage.create(name: "Corneria", legality: "Gentleman")
Stage.create(name: "Flat Zone", legality: "Gentleman")
Stage.create(name: "Fourside", legality: "Gentleman")
Stage.create(name: "Great Bay", legality: "Gentleman")
Stage.create(name: "Green Greens", legality: "Gentleman")
Stage.create(name: "Icicle Mountain", legality: "Gentleman")
Stage.create(name: "Jungle Japes", legality: "Gentleman")
Stage.create(name: "Kongo Jungle", legality: "Gentleman")
Stage.create(name: "Kongo Jungle (N64)", legality: "Gentleman")
Stage.create(name: "Mushroom Kingdom", legality: "Gentleman")
Stage.create(name: "Mushroom Kingdom II", legality: "Gentleman")
Stage.create(name: "Mute City", legality: "Gentleman")
Stage.create(name: "Onett", legality: "Gentleman")
Stage.create(name: "Poké Floats", legality: "Gentleman")
Stage.create(name: "Princess Peach's Castle", legality: "Gentleman")
Stage.create(name: "Rainbow Cruise", legality: "Gentleman")
Stage.create(name: "Temple", legality: "Gentleman")
Stage.create(name: "Vemon", legality: "Gentleman")
Stage.create(name: "Yoshi's Island (pipes)", legality: "Gentleman")
Stage.create(name: "Yoshi's Island (N64)", legality: "Gentleman")

Character.create(name: "Dr. Mario", icon: "/ssbm_icons/dr_mario_icon.jpg")
Character.create(name: "Mario", icon: "/ssbm_icons/mario_icon.jpg")
Character.create(name: "Luigi", icon: "/ssbm_icons/luigi_icon.jpg")
Character.create(name: "Bowser", icon: "/ssbm_icons/bowser_icon.jpg")
Character.create(name: "Peach", icon: "/ssbm_icons/peach_icon.jpg")
Character.create(name: "Yoshi", icon: "/ssbm_icons/yoshi_icon.jpg")
Character.create(name: "Donkey Kong", icon: "/ssbm_icons/donkey_kong_icon.jpg")
Character.create(name: "Captain Falcon", icon: "/ssbm_icons/captain_falcon_icon.jpg")
Character.create(name: "Ganondorf", icon: "/ssbm_icons/ganondorf_icon.jpg")
Character.create(name: "Falco", icon: "/ssbm_icons/falco_icon.jpg")
Character.create(name: "Fox", icon: "/ssbm_icons/fox_icon.jpg")
Character.create(name: "Ness", icon: "/ssbm_icons/ness_icon.jpg")
Character.create(name: "Ice Climbers", icon: "/ssbm_icons/ice_climbers_icon.jpg")
Character.create(name: "Kirby", icon: "/ssbm_icons/kirby_icon.jpg")
Character.create(name: "Samus", icon: "/ssbm_icons/samus_icon.jpg")
Character.create(name: "Zelda", icon: "/ssbm_icons/zelda_icon.jpg")
Character.create(name: "Sheik", icon: "/ssbm_icons/sheik_icon.jpg")
Character.create(name: "Link", icon: "/ssbm_icons/link_icon.jpg")
Character.create(name: "Young Link", icon: "/ssbm_icons/young_link_icon.jpg")
Character.create(name: "Pichu", icon: "/ssbm_icons/pichu_icon.jpg")
Character.create(name: "Pikachu", icon: "/ssbm_icons/pikachu_icon.jpg")
Character.create(name: "Jigglypuff", icon: "/ssbm_icons/jigglypuff_icon.jpg")
Character.create(name: "Mewtwo", icon: "/ssbm_icons/mewtwo_icon.jpg")
Character.create(name: "Mr. Game & Watch", icon: "/ssbm_icons/game_and_watch_icon.jpg")
Character.create(name: "Marth", icon: "/ssbm_icons/marth_icon.jpg")
Character.create(name: "Roy", icon: "/ssbm_icons/roy_icon.jpg")
