#stage population
Stage.create(name: "Final Destination", legality: "Neutral")
Stage.create(name: "Fountain of Dreams", legality: "Neutral")
Stage.create(name: "Battlefield", legality: "Neutral")
Stage.create(name: "Dream Land (N64)", legality: "Neutral")
Stage.create(name: "Yoshi's Story", legality: "Neutral")

Stage.create(name: "Pokémon Stadium", legality: "Counterpick")

Stage.create(name: "Big Blue", legality: "Gentleman")
Stage.create(name: "Brinstar", legality: "Gentleman")
Stage.create(name: "Brinstar Depths", legality: "Gentleman")
Stage.create(name: "Corneria", legality: "Gentleman")
Stage.create(name: "Flat Zone", legality: "Gentleman")
Stage.create(name: "Fourside", legality: "Gentleman")
Stage.create(name: "Great Bay", legality: "Gentleman")
Stage.create(name: "Green Greens", legality: "Gentleman")
Stage.create(name: "Icicle Mountain", legality: "Gentleman")
Stage.create(name: "Jungle Japes", legality: "Gentleman")
Stage.create(name: "Kongo Jungle", legality: "Gentleman")
Stage.create(name: "Kongo Jungle (N64)", legality: "Gentleman")
Stage.create(name: "Mushroom Kingdom", legality: "Gentleman")
Stage.create(name: "Mushroom Kingdom II", legality: "Gentleman")
Stage.create(name: "Mute City", legality: "Gentleman")
Stage.create(name: "Onett", legality: "Gentleman")
Stage.create(name: "Poké Floats", legality: "Gentleman")
Stage.create(name: "Princess Peach's Castle", legality: "Gentleman")
Stage.create(name: "Rainbow Cruise", legality: "Gentleman")
Stage.create(name: "Temple", legality: "Gentleman")
Stage.create(name: "Vemon", legality: "Gentleman")
Stage.create(name: "Yoshi's Island (pipes)", legality: "Gentleman")
Stage.create(name: "Yoshi's Island (N64)", legality: "Gentleman")
